(*
  git hash and date of the last commit 
  auto generated by git_info script
  do not modify by hand
  do not add to git
*)

type git_info = 
    {
     git_sha1 : string;
     git_date : string;
     git_non_committed_changes : bool;
   }


let git_info = 
    {
     git_sha1 = "e2e21e0d95ff15a91e96925232e678bb0e4a6c0a";
     git_date = "2020-08-24 15:53:13 +0200"; 
     git_non_committed_changes =true;
   }

let make_outside_git = ref false;;
