(*
  git hash and date of the last commit 
  auto generated by git_info script
  do not modify by hand
  do not add to git
*)

type git_info = 
    {
     git_sha1 : string;
     git_date : string;
     git_non_committed_changes : bool;
   }


let git_info = 
    {
     git_sha1 = "7264b83b158c550029fafef54d5968cdfd8d9128";
     git_date = "2021-05-07 13:17:07 +0200"; 
     git_non_committed_changes =true;
   }

let make_outside_git = ref false;;
