(*
  git hash and date of the last commit 
  auto generated by git_info script
  do not modify by hand
  do not add to git
*)

type git_info = 
    {
     git_sha1 : string;
     git_date : string;
     git_non_committed_changes : bool;
   }


let git_info = 
    {
     git_sha1 = "abbcfa666aa136f23e8ea4560f3d299031cdd7f7";
     git_date = "2020-08-26 11:01:48 +0200"; 
     git_non_committed_changes =true;
   }

let make_outside_git = ref false;;
