(*
  git hash and date of the last commit 
  auto generated by git_info script
  do not modify by hand
  do not add to git
*)

type git_info = 
    {
     git_sha1 : string;
     git_date : string;
     git_non_committed_changes : bool;
   }


val git_info : git_info
val make_outside_git : bool ref
